name: Gemini Visual Audit

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'angular.json'
      - 'playwright.config.*'

permissions:
  contents: read
  pull-requests: write

jobs:
  gemini-audit:
    runs-on: ubuntu-latest
    if: ${{ secrets.GEMINI_API_KEY != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build and serve SSR
        run: |
          npm run build:ssr:frontend
          timeout 10s npm run serve:ssr:frontend &
          sleep 5
          curl -fsS http://localhost:4000

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Run Gemini Audit
        id: gemini
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            Site SSR Angular 19 em http://localhost:4000.
            Avalie acessibilidade, contraste, hierarquia tipográfica, responsividade, jank no scrollytelling e suporte a reduced-motion.
            Formate em Markdown com: Sumário, Achados Críticos, Melhorias Rápidas, Sugestões.

      - name: Comment PR with Gemini report
        uses: actions/github-script@v7
        with:
          script: |
            const summary = `${{ toJSON(steps.gemini.outputs.summary) }}`.replace(/^"|"$/g,'');
            const body = `## 🤖 Gemini Visual Audit\n\n${summary || 'Sem saída.'}\n`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/**
          retention-days: 7