name: Auto Label (Optional Helper)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Add size label
        uses: actions/github-script@v7
        with:
            script: |
              const files = await github.paginate(github.rest.pulls.listFiles, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                per_page: 100
              });
              const additions = files.reduce((s,f)=>s+f.additions,0);
              let label = 'size/medium';
              if (additions <= 50) label = 'size/tiny';
              else if (additions <= 150) label = 'size/small';
              else if (additions > 400) label = 'size/large';
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });
