name: Visual Regression Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'angular.json'
      - 'playwright.config.*'

permissions:
  contents: read
  pull-requests: write

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:4000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build SSR
        run: npm run build:ssr:frontend

      - name: Start SSR
        run: |
          nohup npm run serve:ssr:frontend > server.log 2>&1 &
          for i in $(seq 1 40); do
            curl -fsS $BASE_URL >/dev/null && break
            sleep 2
          done
          curl -fsS $BASE_URL >/dev/null

      - name: Run visual tests
        run: npx playwright test --grep "(visual|screenshot|baseline)"

      - name: Upload visual diffs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-test-results
          path: |
            test-results/**
            playwright-report/**
          retention-days: 30
